[build]
  publish = ".next"
  command = "npm run build"

[[plugins]]
  package = "@netlify/plugin-nextjs"

  [context.production.environment]
  NEXT_PUBLIC_ANALYTICS_ID = "123"

  [functions]
  node_bundler = "esbuild"